# Configuração do Banco de Dados H2 em Memória
server.port=8081
spring.datasource.url=jdbc:h2:mem:barbeariadb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Atualiza a estrutura das tabelas automaticamente com base nas suas entidades (@Entity)
spring.jpa.hibernate.ddl-auto=update

# Ativa o console visual do H2 no navegador (caso queira ver as tabelas depois)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Mostra os comandos SQL que o JPA criar no terminal (ajuda muito a estudar)
spring.jpa.show-sql=true